# Copyright (C) 2013 Droonga Project
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License version 2.1 as published by the Free Software Foundation.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

source "https://rubygems.org"

vendor_dir = File.join(File.dirname(__FILE__), "vendor")
base_dir = File.join(File.dirname(__FILE__), "../../")

drntest_dir = File.join(vendor_dir, "drntest")
if File.exist?(drntest_dir)
  gem "drntest", :path => drntest_dir
else
  gem "drntest", :github => "droonga/drntest"
end

droonga_client_dir = File.join(vendor_dir, "droonga-client-ruby")
if File.exist?(droonga_client_dir)
  gem "droonga-client", :path => droonga_client_dir
else
  gem "droonga-client", github: "droonga/droonga-client-ruby"
end

gem "fluent-plugin-droonga", :path => base_dir
gem "fluentd"
